# Generated by Django 5.0.6 on 2024-07-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_guestbook_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Эмейл'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='text',
            field=models.TextField(verbose_name='Текст записи'),
        ),
    ]
